version: '3.7'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
      - ./paths:/usr/share/nginx/html/paths
    environment:
      API_URL: openapi.yaml
    ports:
      - "8080:8080"
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
  swagger-api:
    image: stoplight/prism:3
    ports:
      - "8082:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./generated/openapi/openapi.yaml:/openapi.yaml
  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./:/workspace