/* tslint:disable */
/* eslint-disable */
/**
 * API
 * internal_api
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserRole } from './user-role';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * uid
     * @type {string}
     * @memberof User
     */
    'uid': string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * ユーザー名
     * @type {string}
     * @memberof User
     */
    'name': string;
    /**
     * 年齢
     * @type {number}
     * @memberof User
     */
    'age': number;
    /**
     * 
     * @type {UserRole}
     * @memberof User
     */
    'role': UserRole;
    /**
     * ユーザー登録完了フラグ
     * @type {boolean}
     * @memberof User
     */
    'isCompleted': boolean;
    /**
     * 作成日時
     * @type {string}
     * @memberof User
     */
    'createdAt': string;
}



